"""Add is_manager to Message model

Revision ID: 36165b275e17
Revises: <previous_revision_id>
Create Date: 2025-08-21 15:59:34.787058

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '36165b275e17'
down_revision = '<previous_revision_id>'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('is_manager', sa.Boolean(), nullable=False, default=False))
        batch_op.create_foreign_key(
            'fk_message_recipient_id_user',  # Named constraint
            'user',                         # Referenced table
            ['recipient_id'],               # Local column
            ['id'],                         # Referenced column
            ondelete='CASCADE'
        )
        batch_op.drop_column('sender_role')
        batch_op.drop_column('message')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('sender_role', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_message_recipient_id_user', type_='foreignkey')
        batch_op.drop_column('is_manager')
        batch_op.drop_column('content')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###